apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: azimuthingest 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azimuthingest 
    spec:
      containers:
        - name: azimuthingest 
          image: azimuth.azurecr.io/azimuthingest
          ports:
          - containerPort: 80